version: '3.8'

services:
  prestashop:
    image: prestashop/prestashop:8.2
    container_name: prestashop
    environment:
      PS_DOMAIN: ${RAILWAY_STATIC_URL}   # Usar dominio proporcionado por Railway
      PS_INSTALL_DB: 1
      PS_HANDLE_DYNAMIC_DOMAIN: 1
      PS_ENABLE_SSL: 0
      PS_DEV_MODE: 1
      PS_INSTALL_AUTO: 0
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: root_password
      PS_FOLDER_ADMIN: "admin"
      PS_FOLDER_INSTALL: "install"
    ports:
      - "8080:80"                        # No es necesario en Railway, pero útil localmente
    volumes:
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - ./override:/var/www/html/override
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: prestashop_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop_password
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
